### ISSUE TITLE
That shadow...

### ISSUE THREAD

**Issue by vgrenfors** [Lifyzer/Lifyzer-Homepage#3]
That shadow is so annoying I can't read anything on the page..

**Comment by pH-7** [comment]
Hahaha, thanks for the suggestion, but I don't think it is actually a problem.

<img width="900" alt="screen shot 2018-09-03 at 2 02 08 pm" src="https://user-images.githubusercontent.com/1325411/44964104-dd682780-af82-11e8-956f-f94b572a7eca.png">
